### Site info:
name: C++Now!
title: cppnow
tagline: Cppnow 2016
author: C++Now!
email: admin@ciere.com
description: "C++Now! / Boostcon - A gathering of C++ experts and enthusiasts from around the world."
keywords: ""
baseurl: ""
url: "http://cppnow.org"
locale: en_US

### Personal info and site tools info:
twitter_username: ""
github_username: ""
disqus_shortname: 
favicon:     "/images/favicon.ico"
aboutme: All about the cpp. # these are shown on aboutme-sidebar.
aboutme_photo: "" # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

feed:
    path: /feed/


locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "

### your Blogroll info, only name can shown on the page.

Blogroll:
    - name: ""
      href: ""
      title: ""
    - name: ""
      href: ""
      title: ""

gems : [jekyll-paginate, jekyll-feed]

### Build settings
markdown: kramdown
highlighter: pygments
paginate: 5


### Yearly Configuration ###

# The conference year to be home
current_year: 2016-conference
current_dates: "May 9, 2016 - May 14, 2016"
